### ISSUE TITLE
License

### ISSUE THREAD

**Issue by paurkedal** [paurkedal/ppx_regexp#10]
Since the OCaml linking exception was written for LGPL-2, the current license "LGPL-3 with OCaml linking exception" is not clear.  For other projects I have switched to "LGPL-3.0-or-later WITH LGPL-3.0-linking-exception".

@Drup Do you have an opinion about which license to use, and do you agree that we also change the license for `ppx_tyre`?  I plan to make a release of `ppx_regexp` soon, since I updated it to use ppxlib. Should we include `ppx_tyre` even if it's only the license change?  (But I can hold the release if you have other changes.)

**Comment by Drup** [comment]
I don't think "LGPL-3 with OCaml linking exception" is underdefined (iirc, the legwork has been done by ocamlpro at some point to define what it means), so I think this is rather pedantic and useless, but if you feel reassured doing that, I don't have any opposition, you can go forth. :p

**Comment by paurkedal** [comment]
Nice, I was not aware of that.  Do you know if the published it somewhere?  Searching, I found a reformulation at the bottom of https://gitlab.com/o-labs/solidity-parser-ocaml/-/blob/master/LICENSE, so that's probably the phrasing, unless they revised it.
